config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :users, only: [:edit, :update]
  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end
 
  resources :orders, only: [:create, :show]
  
  post 'cart/remove_product/:product_id', to: 'carts#remove_product', as: 'remove_product_cart'

  namespace :admin do
    root to: 'dashboard#show'
    resources :products
    resources :categories
  end

  get '/about' => 'about#index'

  # These routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: :logout


  # These routes are for signup. The first renders a form in the browser, the second will 
  # receive the form and create a user in our database using the data given to us by the user.
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
end
 

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :require_login, only: [:show]

  def show
    @cart_items = enhanced_cart
    @subtotal = cart_subtotal_cents / 100.0
    @taxes = calculate_taxes(current_user) if current_user.present?
    @total = @subtotal + @taxes.values.sum
  end

  def add_item
    product_id = params[:product_id].to_s
    cart = update_cart_delta(product_id, +1)
    update_cart(cart)
    redirect_back(fallback_location: root_path)
  end

  def remove_item
    product_id = params[:product_id].to_s
    cart = update_cart_delta(product_id, -1)
    update_cart(cart)
    redirect_back(fallback_location: root_path)
  end

  def remove_product
    product_id = params[:product_id].to_s
    cart = update_cart_delta(product_id, 0)  
    update_cart(cart)
    redirect_back(fallback_location: root_path)
  end

  private

  def modify_cart_delta(product_id, delta)
    cart[product_id] = (cart[product_id] || 0) + delta
    cart.delete(product_id) if cart[product_id] < 1
    update_cart cart
  end

  def update_cart_delta(product_id, delta)
    cart[product_id] ||= 0
    cart[product_id] += delta
    cart.delete(product_id) if cart[product_id] <= 0
    cart
  end

  def calculate_taxes(user)
    return { gst: 0, pst: 0, hst: 0 } unless user&.province
    tax_rates = user.province.tax_rates || {}

    gst = tax_rates['gst'].to_f
    pst = tax_rates['pst'].to_f
    hst = tax_rates['hst'].to_f

    {
      gst: @subtotal * gst,
      pst: @subtotal * pst,
      hst: @subtotal * hst
    }
  end
end

app/views/carts/_item.html.erb
<tr>
  <td>
    <%= image_tag product.image.tiny.url %>
  </td>
  <td>
    <h4><%= product.name %></h4>
    <br>
    <p><%= product.description %></p>
  </td>
  <td>
    <%= humanized_money_with_symbol product.price %>
  </td>
  <td>
    <div>
    <%= button_to remove_item_cart_path(product_id: product.id), class: 'btn btn-xs btn-danger' do %> - <% end %>
    <%= quantity %>
    <%= button_to add_item_cart_path(product_id: product.id), class: 'btn btn-xs btn-success' do %> + <% end %>
    </div>
    <div>
    <%= button_to remove_product_cart_path(product_id: product.id), method: :post, class: 'btn btn-xs btn-danger' do %>
      Remove
    <% end %>
    </div>
  </td>
  <td>
    <%= humanized_money_with_symbol product.price * quantity %>
  </td>
</tr>

app/views/carts/show.html.erb
<section class="cart-show">

  <header class="page-header">
    <h1>My Cart</h1>
  </header>

  <% if @cart_items.empty? %>
    <div class="alert alert-danger">
      Your cart is empty.
      Click <a href="/">here</a> to return to the homepage.    
    </div>
  <% else %>

    <div class="panel panel-default items">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th colspan="2">Product</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
          <% @cart_items.each do |item| %>
            <%= render 'item', product: item[:product], quantity: item[:quantity].to_i %>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <th colspan="4">Subtotal:</th>
            <th><%= number_to_currency @subtotal %></th> 
          </tr>
          <% if @taxes %>
            <% if @taxes[:gst] > 0 %>
              <tr>
                <th colspan="4">GST:</th>
                <th><%= number_to_currency @taxes[:gst] %></th>
              </tr>
            <% end %>
            <% if @taxes[:pst] > 0 %>
              <tr>
                <th colspan="4">PST:</th>
                <th><%= number_to_currency @taxes[:pst] %></th>
              </tr>
            <% end %>
            <% if @taxes[:hst] > 0 %>
              <tr>
                <th colspan="4">HST:</th>
                <th><%= number_to_currency @taxes[:hst] %></th>
              </tr>
            <% end %>
          <% end %>
          <tr>
            <th colspan="4">TOTAL:</th>
            <th><%= number_to_currency(@subtotal + @taxes.values.sum) %></th>
          </tr>
        </tfoot>
      </table>
    </div>

    <div class="row">
    <div class="col-xs-12">
      <%= form_tag orders_path do %>
        <div class="form-group">
          <label for="order_province">Province:</label>
          <select name="order[province]" id="order_province" class="form-control">
            <% Province.all.each do |province| %>
              <option value="<%= province.id %>"><%= province.name %></option>
            <% end %>
          </select>
        </div>

        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-amount="<%= (@subtotal + @taxes.values.sum) * 100 %>"
          data-name="Earls Order"
          data-description="Checkout Order"
          data-locale="auto"
          data-currency="cad">
        </script>
      <% end %>
    </div>
  </div>


  </section>
<% end %>