config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :users, only: [:edit, :update]
  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end
 
  resources :orders, only: [:create, :show]
  
  post 'cart/remove_product/:product_id', to: 'carts#remove_product', as: 'remove_product_cart'

  namespace :admin do
    root to: 'dashboard#show'
    resources :products
    resources :categories
  end

  get '/about' => 'about#index'

  # These routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: :logout


  # These routes are for signup. The first renders a form in the browser, the second will 
  # receive the form and create a user in our database using the data given to us by the user.
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
end
 

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  http_basic_authenticate_with name: ENV['BASIC_AUTH_USERNAME'], password: ENV['BASIC_AUTH_PASSWORD']

  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end


  def edit
    @product = Product.find(params[:id])
  end


  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to [:admin, @product], notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def show
    @product = Product.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Product not found."
    redirect_to admin_products_path
  end
  

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductHelper

  def index
    
    @products = if params[:category_id].present?
                  Category.find(params[:category_id]).products
                else
                  Product.all
                end

    # Filter by search keyword if provided
    if params[:search].present?
      @products = @products.where("name LIKE :search OR description LIKE :search", search: "%#{params[:search]}%")
    end

    # Continue with the existing ordering and pagination
    @products = @products.order(created_at: :desc).page(params[:page]).per(6)
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/product_helper.rb
module ProductHelper

  def out_of_stock?(product)
    product.quantity.zero?
  end
  
end

app/views/admin/products/_product.html.erb
<tr>
  <td>
    <%= image_tag product.image.tiny.url %>
  </td>
  <td>
    <h4><%= product.name %></h4>
    <br>
    <p><%= product.description %></p>
  </td>
  <td>
    <%= product.category.name %>
  </td>
  <td>
    <%= humanized_money_with_symbol product.price %>
  </td>
  <td>
    <%= product.quantity %>
  </td>
  <td>
    <%= link_to fa_icon('trash'), [:admin, product], class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: "Are you sure?" } %>
    <%= link_to fa_icon('edit'), edit_admin_product_path(product), class: 'btn btn-sm btn-primary', data: { toggle: "tooltip", placement: "top" }, title: "Edit Product" %>

  </td>
</tr>

app/views/admin/products/edit.html.erb
<%= form_for [:admin, @product], html: { multipart: true } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <% if @product.image? %>
      <%= image_tag(@product.image.url) %>
      <p>Change Image:</p>
    <% end %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', products_path %>

app/views/admin/products/index.html.erb
<section class="admin-products-index">

  <header class="page-header">
    <h1>Admin &raquo; All Products</h1>
  </header>

  <div class="well">
    <p>
      <%= link_to '+ New Product', [:new, :admin, :product], class: 'btn btn-lg btn-success' %>
    </p>
  </div>

  <div class="panel panel-default products">

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Category</th>
          <th>Price</th>
          <th>Qty Remaining</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @products %>
      </tbody>
    </table>

  </div>

</section>

app/views/admin/products/new.html.erb
<section class="admin-products-new">

  <header class="page-header">
    <h1>Admin &raquo; New Product</h1>
  </header>

  <div class="well">
    <p>
    <%= link_to 'Show All Products', [:admin, :products], class: 'btn btn-lg btn-success' %>
    </p>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @product] do |form| %>

        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :category %>
          <%= form.select :category_id, options_from_collection_for_select(Category.all.order(:name), :id, :name), { include_blank: true }, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :quantity %>
          <%= form.number_field :quantity, class: 'form-control' %>
        </div>

        <div class="form-group">
          <p>
          <%= form.label :price %>
          <%= form.text_field :price, class: 'form-control' %>
          </p>
        </div>



        <div class="form-group">
          <p>
          <%= form.label :image %>
          <%= form.file_field :image %>
          </p>
        </div>

        <%= form.submit 'Create Product', class: 'btn btn-lg btn-success' %>
      <% end %>
    </div>
  </div>

</section>

app/views/admin/products/show.html.erb
<h1>Product Details</h1>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price) %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>

<% if @product.image? %>
  <p>
    <strong>Image:</strong>
    <%= image_tag(@product.image.url) %>
  </p>
<% end %>

<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back to List', admin_products_path %>