config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :users, only: [:edit, :update]
  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end
 
  resources :orders, only: [:create, :show]
  
  post 'cart/remove_product/:product_id', to: 'carts#remove_product', as: 'remove_product_cart'

  namespace :admin do
    root to: 'dashboard#show'
    resources :products
    resources :categories
  end

  get '/about' => 'about#index'

  # These routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: :logout


  # These routes are for signup. The first renders a form in the browser, the second will 
  # receive the form and create a user in our database using the data given to us by the user.
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
end
 

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  http_basic_authenticate_with name: ENV['BASIC_AUTH_USERNAME'], password: ENV['BASIC_AUTH_PASSWORD']

  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end


  def edit
    @product = Product.find(params[:id])
  end


  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to [:admin, @product], notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def show
    @product = Product.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Product not found."
    redirect_to admin_products_path
  end
  

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductHelper

  def index
    
    @products = if params[:category_id].present?
                  Category.find(params[:category_id]).products
                else
                  Product.all
                end

    # Filter by search keyword if provided
    if params[:search].present?
      @products = @products.where("name LIKE :search OR description LIKE :search", search: "%#{params[:search]}%")
    end

    # Continue with the existing ordering and pagination
    @products = @products.order(created_at: :desc).page(params[:page]).per(6)
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/product_helper.rb
module ProductHelper

  def out_of_stock?(product)
    product.quantity.zero?
  end
  
end

app/views/products/_product.html.erb
<article>
  <%= link_to product_path(product) do %>
  <%= image_tag product.image.thumb.url , alt: product.name %>
  <h1>
    <span><%= product.name %></span>
    <span><%= humanized_money_with_symbol product.price %></span>
  </h1>
  <% end%>
  <div>
    <% if out_of_stock?(product) %>
    <button class="soldout">Sold Out</button>
    <% else %>
    <%= button_to add_item_cart_path(product_id: product.id), class: 'btn' ,
      method: :post do %>
    <%= fa_icon "shopping-cart", text: 'Add' %>
    <% end %>
    <% end %>
  </div>

</article>

app/views/products/index.html.erb
<section class="products-index">
  <header class="page-header">
    <div class="intro">
      <p>
        Earls offers a captivating dining experience, blending traditional Indian flavors with a modern twist...
      </p>
      <p>
        At Earls guests are treated to an exquisite journey through Indian culinary heritage...
      </p>
      <p>
        We have a wide variety of dish menu available for purchase on our website. Whether you are looking...
      </p>
    </div>
  </header>


  <%= form_with url: products_path, method: :get, local: true do |form| %>
    <div class="search-form">
      <%= form.label :search, "Search for a product:" %>
      <%= form.text_field :search, value: params[:search], placeholder: "Keyword" %>

      <%= form.label :category_id, "Choose a category:" %>
      <%= form.collection_select :category_id, Category.all, :id, :name, include_blank: 'All Categories' %>

      <%= form.submit "Search" %>
    </div>
  <% end %>

  
  <div class="products">
    <%= render @products %>
  </div>

  <%= paginate @products %>
</section>

app/views/products/show.html.erb
<section class="products-show">
  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">
    <%= image_tag @product.image.url, class: 'main-img' %>
    <div>
      <h1><%= @product.name %></h1>
      <p><%= @product.description %></p>
      <div class="quantity">
        <% if out_of_stock?(@product) %>
        <button class="soldout">Sold Out</button>
        <% else %>
        <span><%= @product.quantity %> in stock at </span>
        <span><%= humanized_money_with_symbol @product.price %></span>
      </div>
      <div class="price">          
        <%= button_to add_item_cart_path(product_id: @product.id), class: 'btn' , method: :post do %>
        <%= fa_icon "shopping-cart", text: 'Add' %>
        <% end %>
        <% end %>          
      </div>
    </div>
  </article>
</section>